export const orders = [
  {
    id: '60666c42cc7b410027a1a9b1',
    name: 'Краторная булка N-200i',
    number: '#456456',
    data: 'Сегодня, 16:20',
    images: [
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',

    ],
    price: 5040,
  },
  {
    id: '60666c42cc7b410027a1a9b5',
    name: 'Говяжий метеорит (отбивная)',
    number: '#412356',
    data: 'Вчера, 17:20',
    images: [
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    ],
    price: 5020,
  },
  {
    id: '60666c42cc7b410027a1a9b6',
    name: 'Биокотлета из марсианской Магнолии',
    number: '#412356',
    data: 'Вчера, 17:20',
    images: [
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    ],
    price: 5040,
  },
  {
    id: '60666c42cc7b410027a1a9b7',
    name: 'Соус Spicy-X',
    number: '#412356',
    data: 'Вчера, 17:20',
    images: [
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    ],
    price: 5021,
  },
  {
    id: '60666c42cc7b410027a1a9b4',
    name: 'Мясо бессмертных моллюсков Protostomia',
    number: '#410056',
    data: 'Вчера, 17:20',
    images: [
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    ],
    price: 5300,
  },
  {
    id: '60666c42cc7b410027a1a9b9',
    name: 'Соус традиционный галактический',
    number: '#892356',
    data: 'Вчера, 17:20',
    images: [
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
      'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
      'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
      'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    ],
    price: 600,
  },
];
